load("//util:test.bzl", "ts_test")

ts_test(test_file = "foo_test.ts")
ts_test(test_file = "bar_test.ts")
ts_test(test_file = "transform_test.ts")
ts_test(test_file = "scenario_test.ts", more_data=["//scenarios/01_basic_messages:expected.d.ts"])
