load("//util:protoc.bzl", "proto_to_ts_interfaces")
proto_to_ts_interfaces(["plain_email.proto", "plain_email_bonus.proto", "html_email.proto"])
exports_files(["expected.d.ts", "html_email.proto", "plain_email.proto", "plain_email_bonus.proto"])